<h1 style='color: red'>Span Email Detection</h1>

Naive Bayes, is one the technique to detect the span emails, by finding the unique words from the email message, and getting the number of occurance list for that words, 

<img src='detection_methods.png' width=500>

In [43]:
# importing the modules
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

In [3]:
# load the dataset
dataset = pd.read_csv('spam.csv')
dataset.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
dataset.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [12]:
dataset['spam'] = dataset['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [13]:
dataset.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [32]:
# splitting training and testing datasets
x_train, x_test, y_train, y_test = train_test_split(dataset['Message'], dataset['spam'], test_size=0.3, random_state=7)

But the Machine Learning Algorithm dosen't takes text as inputs,

In [33]:
v = CountVectorizer()
x_train_count = v.fit_transform(x_train.values)
x_test_count = v.transform(x_test.values)

In [34]:
x_train_count.toarray(), x_test_count.toarray()

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64))

In [35]:
# creating the model
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [36]:
model.score(x_test_count, y_test)

0.986244019138756

### Predicting the sample emails

1. Hey mohan, can we get together to watch footbal game tomorrow?
2. Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!


In [37]:
email = [
    'Hey mohan, can we get together to watch footbal game tomorrow?', 
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

email_counts = v.transform(email)

In [38]:
model.predict(email_counts)

array([0, 1], dtype=int64)

<h1 style='color: red'>Feature of Using sklearn Pipeline</h1>

pipeline will automate the process of count vectorizer, process of transforming the values

In [58]:
model_pipeline = Pipeline([
    ('vectorization', CountVectorizer()),
    ('model', MultinomialNB())
])

In [59]:
model_pipeline.fit(x_train, y_train)

Pipeline(steps=[('vectorization', CountVectorizer()),
                ('model', MultinomialNB())])

In [60]:
email = [
    'Hey mohan, can we get together to watch footbal game tomorrow?', 
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [61]:
email

['Hey mohan, can we get together to watch footbal game tomorrow?',
 'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!']

In [62]:
model_pipeline.score(x_test, y_test)

0.986244019138756

In [63]:
model_pipeline.predict(email)

array([0, 1], dtype=int64)